name: quran_app
description: A Quran reading app
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # API & Network
  http: ^1.2.0

  # UI
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  google_fonts: ^6.1.0

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Audio
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/quran/quran_arabic.json
    - assets/data/quran/quran_english.json

  fonts:
    - family: IndoPak
      fonts:
        - asset: assets/fonts/font.ttf

  # fonts:
  #   - family: KFGQPCNaskh
  #     fonts:
  #       - asset: assets/fonts/KFGQPC Uthman Taha Naskh Regular.ttf

    # (optional) keep your old one only if it still exists
    # - family: UthmanicHafs
    #   fonts:
    #     - asset: assets/fonts/UthmanicHafs.otf